#!/usr/bin/env python

import os
import sys
import re


def advance_to_regex(lines, regex, n):
    m = None
    while n < len(lines):
        m = re.search(regex, lines[n])
        if m is not None:
            break
        n += 1
    assert m is not None, "Could not find regex /{0}/".format(regex)
    return n


for line in sys.stdin.readlines():
    line = line.rstrip()
    if len(line) < 1 or line[0] != '@':
        # not a preprocessor line
        print line
        continue
    line = line[1:]
    n = line.index(":")
    fn, line = line[:n], line[n+1:]
    assert os.path.isfile(fn)
    lines = [L.rstrip() for L in open(fn).readlines()]
    sequence = line.split("/")   # escape slashes in regexes??
    n = 0
    for regex in sequence[:-2]:
        n = advance_to_regex(lines, regex, n)
    sregex, fregex = sequence[-2:]
    m = advance_to_regex(lines, sregex, n)
    n = advance_to_regex(lines, fregex, m)
    for L in lines[m:n+1]:
        print L